### ISSUE TITLE
Error resolving template “home”, template might not exist or might not be accessible by any of the configured Template Resolvers

### ISSUE THREAD

**Issue by vdnhat** [thymeleaf/thymeleafexamples-stsm#1]
I'm using mvc + java HttpServlet + Thymeleaf template but it's error. File home.html has exist.

My code bellow:

```
    ServletContextTemplateResolver templateResolver 
                = new ServletContextTemplateResolver();
    // XHTML is the default mode, but we will set it anyway for better understanding of code
    templateResolver.setTemplateMode("HTML5");
    templateResolver.setPrefix("D:\\development\\projects\\fpt.eclick.framework.web.thyme\\views\\");
    templateResolver.setSuffix(".html");
    templateResolver.setCacheTTLMs(3600000L);
    TemplateEngine templateEngine = new TemplateEngine();
    templateEngine.setTemplateResolver(templateResolver);
    WebContext ctx = new WebContext(request, response, request.getServletContext(), request.getLocale());

    try {
        templateEngine.process("home", ctx, response.getWriter());
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    response.setContentType("text/html;charset=UTF-8");
    response.setHeader("Pragma", "no-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 1000);
```

With Freemarker I used similar to and it's well done.

Image code attach in file
![done](https://cloud.githubusercontent.com/assets/6857869/2697577/0612b3d6-c3f0-11e3-825a-6b628096449d.png)

Thank you very much

**Comment by danielfernandez** [comment]
The `ServletContextTemplateResolver` tries to resolve your templates from the web application's root (or _servlet context root_), so `prefix` usually looks something like `/WEB-INF/templates/thymeleaf/`, for example.

But you have `/src/main/resources/thymeleaf/`, which looks more like the path to your templates at your project's source code.

**Comment by lqjack** [comment]
hi,how to fill the templateResolver.setPrefix ,thanks a lot.

**Comment by Xikl** [comment]
me too

**Comment by MasterChris27** [comment]
private final ThymeleafProperties thymeleafProperties;

    @Autowired
    public ThymeleafConfig(ThymeleafProperties thymeleafProperties) {
        this.thymeleafProperties = thymeleafProperties;
    }
...
resolver.setPrefix(this.thymeleafProperties.getPrefix());

or you could use "classpath:/thymeleaf" . that will work too :)

**Comment by MotamenGhanoum** [comment]
.
